package com.SchoolManagementSystem.Views;

import javax.swing.table.DefaultTableModel;

import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import com.SchoolManagementSystem.Views.DashboardView;

import com.SchoolManagementSystem.Dtos.ClassesDto;
import com.SchoolManagementSystem.Helpers.CachingService;
import com.SchoolManagementSystem.Repositories.ClassesRepositories;

public class ClassView extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    
    // Classes Repositories
    private final ClassesRepositories classRepositories =
        new ClassesRepositories();
    
    // Classes DTOs
    private ClassesDto classesDto = new ClassesDto();
    
    private ArrayList<String> classIdLists = new ArrayList<>();
    
    public ClassView() {
        initComponents();
        this.setTitle("Data Kelas");
        TableHandler("default", null);
    }
    
    private void TableHandler(String mode, String search) {
        tableModel = new DefaultTableModel();
        ClassesTable.setModel(tableModel);
        
        String[] columnNames = {
            "Nomor",
            "Nama Kelas",
            "Kapasitas Kelas"
        };
        
        tableModel.setColumnIdentifiers(columnNames);
        
        List<ClassesDto> classesDataList;
        if (mode.equals("searching")) {
            classesDataList = classRepositories
                .searchClassesRepository(search);
        } else {
            classesDataList = classRepositories
            .getClassesRepository();
        }
        
        int index = 1;
        classIdLists = new ArrayList<>();
        for (ClassesDto classData : classesDataList) {
            String classId         = classData.getClassId();
            String className       = classData.getClassName();
            String classCapacity   = classData.getClassCapacity();
            
            tableModel.addRow(new Object[]{
                index, className, classCapacity
            });
            
            classIdLists.add(classId);
            index ++;
        }
    }
    
    private void postAction(boolean condition, String message) {
        classesDto = new ClassesDto();
        CachingService.clear();
        TableHandler("default", null);
        
        if (condition) {
            JOptionPane.showMessageDialog(
                this, 
                message,
                "Berhasil...",
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                this, 
                message,
                "Gagal...",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameRoomLabel = new javax.swing.JLabel();
        ClassNameTextField = new javax.swing.JTextField();
        WideRoomLabel = new javax.swing.JLabel();
        ClassCapacityTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClassesTable = new javax.swing.JTable();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameRoomLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        NameRoomLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel.setText("Nama Kelas");

        ClassNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClassNameTextField.setForeground(new java.awt.Color(86, 85, 191));
        ClassNameTextField.setText("  Masukan Nama Kelas ...");
        ClassNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        ClassNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClassNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassNameTextFieldActionPerformed(evt);
            }
        });

        WideRoomLabel.setBackground(new java.awt.Color(0, 0, 0));
        WideRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WideRoomLabel.setForeground(new java.awt.Color(86, 85, 191));
        WideRoomLabel.setText("Kapasitas");

        ClassCapacityTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClassCapacityTextField.setForeground(new java.awt.Color(86, 85, 191));
        ClassCapacityTextField.setText("  Masukan Kapasitas Kelas ...");
        ClassCapacityTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        ClassCapacityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassCapacityTextFieldActionPerformed(evt);
            }
        });

        ClassesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClassesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nomor", "Nama Kelas", "Kapasitas Kelas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClassesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassesTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ClassesTable);

        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(86, 85, 191));
        SearchTextField.setText("  Cari Kelas ...");
        SearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(86, 85, 191));
        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Cari");
        SearchButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(86, 85, 191));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Tambah");
        AddButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(86, 85, 191));
        ResetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(86, 85, 191));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Hapus");
        DeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(86, 85, 191));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setText("Edit");
        EditButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(86, 85, 191));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Kelas");

        NameRoomLabel1.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        NameRoomLabel1.setText("  Kembali  ");
        NameRoomLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        NameRoomLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NameRoomLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameRoomLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NameRoomLabel1)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameRoomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WideRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassNameTextField)
                    .addComponent(ClassCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(NameRoomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClassNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(WideRoomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClassCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClassNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassNameTextFieldActionPerformed

    private void ClassCapacityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassCapacityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassCapacityTextFieldActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void ClassesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassesTableMouseClicked
        int selectedRow = ClassesTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane
                .showMessageDialog(this, 
                "Pilih baris yang ingin diupdate.");
        }
        
        CachingService.put("classId", classIdLists.get(
                (int) tableModel.getValueAt(selectedRow, 0) - 1
            )
        );
        
        ClassNameTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 1));
        ClassCapacityTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 2));
    }//GEN-LAST:event_ClassesTableMouseClicked

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        classesDto.setClassName(ClassNameTextField.getText());
        classesDto.setClassCapacity(ClassCapacityTextField.getText());
        
        Map<String, Object> createClass = classRepositories
            .createClassRepository(classesDto);
        
        postAction(
            (boolean) createClass.get("result"),
            (String) createClass.get("message")
        );
    }//GEN-LAST:event_AddButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        ClassNameTextField.setText("  Masukan Nama Kelas ...");
        ClassCapacityTextField.setText("  Masukan Kapasitas Kelas ...");
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        boolean deleteClass = classRepositories
            .deleteClassRepository((String) CachingService.get("classId"));
        
        postAction(
            deleteClass,
            "Data Berhasil Di Hapus !!!."
        );
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        classesDto.setClassId((String) CachingService.get("classId"));
        classesDto.setClassName(ClassNameTextField.getText());
        classesDto.setClassCapacity(ClassCapacityTextField.getText());
        
        Map<String, Object> updateClass = classRepositories
            .updateClassRepository(classesDto);
        
        postAction(
            (boolean) updateClass.get("result"),
            (String) updateClass.get("message")
        );
    }//GEN-LAST:event_EditButtonMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        TableHandler("searching", SearchTextField.getText());
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void NameRoomLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameRoomLabel1MouseClicked
        DashboardView dashboardView = new DashboardView();
            
        dashboardView.setVisible(true);
        dashboardView.setResizable(false);
        dashboardView.pack();
        dashboardView.setLocationRelativeTo(null);
        dashboardView.setDefaultCloseOperation(dashboardView.EXIT_ON_CLOSE);

        this.setVisible(false);
    }//GEN-LAST:event_NameRoomLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField ClassCapacityTextField;
    private javax.swing.JTextField ClassNameTextField;
    private javax.swing.JTable ClassesTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel NameRoomLabel;
    private javax.swing.JLabel NameRoomLabel1;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel WideRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
