package com.SchoolManagementSystem.Views;

import javax.swing.table.DefaultTableModel;

import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import com.SchoolManagementSystem.Views.AuthView;
import com.SchoolManagementSystem.Views.ClassView;
import com.SchoolManagementSystem.Views.StudentView;
import com.SchoolManagementSystem.Views.SubjectView;
import com.SchoolManagementSystem.Views.EmployeeView;
import com.SchoolManagementSystem.Views.SubjectScheduleView;
import com.SchoolManagementSystem.Views.StudentAttendanceView;
import com.SchoolManagementSystem.Views.EmployeeAttendanceView;

import com.SchoolManagementSystem.Repositories.AuthRepositories;

public class DashboardView extends javax.swing.JFrame {
    
    // Classes Repositories
    private final AuthRepositories authRepositories =
        new AuthRepositories();
    
    public DashboardView() {
        initComponents();
        this.setTitle("Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JLabel();
        ClassFeature = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SubjectFeature = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StudentDataFeature = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        StudentFeature = new javax.swing.JLabel();
        EmployeeFeature = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SubjectScheduleFeature = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmployeeAttendanceFeature = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        StudentAttendanceFeature = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(86, 85, 191));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistem Informasi Sekolah");

        LogoutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("   Keluar   ");
        LogoutButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        ClassFeature.setBackground(new java.awt.Color(86, 85, 191));
        ClassFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClassFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassFeatureMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\icon.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Kelas");

        javax.swing.GroupLayout ClassFeatureLayout = new javax.swing.GroupLayout(ClassFeature);
        ClassFeature.setLayout(ClassFeatureLayout);
        ClassFeatureLayout.setHorizontalGroup(
            ClassFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassFeatureLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClassFeatureLayout.setVerticalGroup(
            ClassFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClassFeatureLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(ClassFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(ClassFeatureLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(15, 15, 15))
        );

        SubjectFeature.setBackground(new java.awt.Color(86, 85, 191));
        SubjectFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubjectFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubjectFeatureMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\subject.png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mata Pelajaran");

        javax.swing.GroupLayout SubjectFeatureLayout = new javax.swing.GroupLayout(SubjectFeature);
        SubjectFeature.setLayout(SubjectFeatureLayout);
        SubjectFeatureLayout.setHorizontalGroup(
            SubjectFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectFeatureLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        SubjectFeatureLayout.setVerticalGroup(
            SubjectFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectFeatureLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectFeatureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(43, 43, 43))
        );

        StudentDataFeature.setBackground(new java.awt.Color(86, 85, 191));
        StudentDataFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentDataFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentDataFeatureMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\student.png")); // NOI18N

        StudentFeature.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        StudentFeature.setForeground(new java.awt.Color(255, 255, 255));
        StudentFeature.setText("Data Siswa");

        javax.swing.GroupLayout StudentDataFeatureLayout = new javax.swing.GroupLayout(StudentDataFeature);
        StudentDataFeature.setLayout(StudentDataFeatureLayout);
        StudentDataFeatureLayout.setHorizontalGroup(
            StudentDataFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDataFeatureLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StudentFeature)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        StudentDataFeatureLayout.setVerticalGroup(
            StudentDataFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDataFeatureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StudentDataFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentDataFeatureLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentDataFeatureLayout.createSequentialGroup()
                        .addComponent(StudentFeature)
                        .addGap(37, 37, 37))))
        );

        EmployeeFeature.setBackground(new java.awt.Color(86, 85, 191));
        EmployeeFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeFeatureMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\teacher.png")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Guru dan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pegawai");

        javax.swing.GroupLayout EmployeeFeatureLayout = new javax.swing.GroupLayout(EmployeeFeature);
        EmployeeFeature.setLayout(EmployeeFeatureLayout);
        EmployeeFeatureLayout.setHorizontalGroup(
            EmployeeFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeFeatureLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(EmployeeFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeFeatureLayout.setVerticalGroup(
            EmployeeFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeFeatureLayout.createSequentialGroup()
                .addGroup(EmployeeFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeFeatureLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(EmployeeFeatureLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubjectScheduleFeature.setBackground(new java.awt.Color(86, 85, 191));
        SubjectScheduleFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubjectScheduleFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubjectScheduleFeatureMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\schdule.png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jadwal Mata   ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pelajaran");

        javax.swing.GroupLayout SubjectScheduleFeatureLayout = new javax.swing.GroupLayout(SubjectScheduleFeature);
        SubjectScheduleFeature.setLayout(SubjectScheduleFeatureLayout);
        SubjectScheduleFeatureLayout.setHorizontalGroup(
            SubjectScheduleFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectScheduleFeatureLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(SubjectScheduleFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );
        SubjectScheduleFeatureLayout.setVerticalGroup(
            SubjectScheduleFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectScheduleFeatureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SubjectScheduleFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectScheduleFeatureLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectScheduleFeatureLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(26, 26, 26))))
        );

        EmployeeAttendanceFeature.setBackground(new java.awt.Color(86, 85, 191));
        EmployeeAttendanceFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeAttendanceFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeAttendanceFeatureMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\attend.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Absensi Guru");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("dan Pegawai");

        javax.swing.GroupLayout EmployeeAttendanceFeatureLayout = new javax.swing.GroupLayout(EmployeeAttendanceFeature);
        EmployeeAttendanceFeature.setLayout(EmployeeAttendanceFeatureLayout);
        EmployeeAttendanceFeatureLayout.setHorizontalGroup(
            EmployeeAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAttendanceFeatureLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(EmployeeAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeAttendanceFeatureLayout.setVerticalGroup(
            EmployeeAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeAttendanceFeatureLayout.createSequentialGroup()
                .addGroup(EmployeeAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeAttendanceFeatureLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14))
                    .addGroup(EmployeeAttendanceFeatureLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        StudentAttendanceFeature.setBackground(new java.awt.Color(86, 85, 191));
        StudentAttendanceFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentAttendanceFeature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentAttendanceFeatureMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon("F:\\projects\\application projects\\school_management_system\\icons\\att_student.png")); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Absensi Siswa");

        javax.swing.GroupLayout StudentAttendanceFeatureLayout = new javax.swing.GroupLayout(StudentAttendanceFeature);
        StudentAttendanceFeature.setLayout(StudentAttendanceFeatureLayout);
        StudentAttendanceFeatureLayout.setHorizontalGroup(
            StudentAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentAttendanceFeatureLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(20, 20, 20))
        );
        StudentAttendanceFeatureLayout.setVerticalGroup(
            StudentAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentAttendanceFeatureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StudentAttendanceFeatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentAttendanceFeatureLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentAttendanceFeatureLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ClassFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubjectScheduleFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeeAttendanceFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentDataFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeeFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentAttendanceFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(SubjectFeature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ClassFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentDataFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubjectFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentAttendanceFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeAttendanceFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubjectScheduleFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClassFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassFeatureMouseClicked
        ClassView classFormView = new ClassView();
            
        classFormView.setVisible(true);
        classFormView.setResizable(false);
        classFormView.pack();
        classFormView.setLocationRelativeTo(null);
        classFormView.setDefaultCloseOperation(classFormView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_ClassFeatureMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        AuthView authView = new AuthView();
            
        authView.setVisible(true);
        authView.setResizable(false);
        authView.pack();
        authView.setLocationRelativeTo(null);
        authView.setDefaultCloseOperation(authView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void SubjectFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubjectFeatureMouseClicked
        SubjectView subjectView = new SubjectView();
            
        subjectView.setVisible(true);
        subjectView.setResizable(false);
        subjectView.pack();
        subjectView.setLocationRelativeTo(null);
        subjectView.setDefaultCloseOperation(subjectView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_SubjectFeatureMouseClicked

    private void StudentDataFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDataFeatureMouseClicked
        StudentView studentView = new StudentView();
            
        studentView.setVisible(true);
        studentView.setResizable(false);
        studentView.pack();
        studentView.setLocationRelativeTo(null);
        studentView.setDefaultCloseOperation(studentView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_StudentDataFeatureMouseClicked

    private void EmployeeFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeFeatureMouseClicked
        EmployeeView employeeView = new EmployeeView();
            
        employeeView.setVisible(true);
        employeeView.setResizable(false);
        employeeView.pack();
        employeeView.setLocationRelativeTo(null);
        employeeView.setDefaultCloseOperation(employeeView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_EmployeeFeatureMouseClicked

    private void SubjectScheduleFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubjectScheduleFeatureMouseClicked
        SubjectScheduleView subjectScheduleView = new SubjectScheduleView();
            
        subjectScheduleView.setVisible(true);
        subjectScheduleView.setResizable(false);
        subjectScheduleView.pack();
        subjectScheduleView.setLocationRelativeTo(null);
        subjectScheduleView.setDefaultCloseOperation(subjectScheduleView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_SubjectScheduleFeatureMouseClicked

    private void EmployeeAttendanceFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeAttendanceFeatureMouseClicked
        EmployeeAttendanceView employeeAttendanceView = new EmployeeAttendanceView();
            
        employeeAttendanceView.setVisible(true);
        employeeAttendanceView.setResizable(false);
        employeeAttendanceView.pack();
        employeeAttendanceView.setLocationRelativeTo(null);
        employeeAttendanceView.setDefaultCloseOperation(employeeAttendanceView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_EmployeeAttendanceFeatureMouseClicked

    private void StudentAttendanceFeatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentAttendanceFeatureMouseClicked
        StudentAttendanceView studentAttendanceView = new StudentAttendanceView();
            
        studentAttendanceView.setVisible(true);
        studentAttendanceView.setResizable(false);
        studentAttendanceView.pack();
        studentAttendanceView.setLocationRelativeTo(null);
        studentAttendanceView.setDefaultCloseOperation(studentAttendanceView.EXIT_ON_CLOSE);
        
        this.setVisible(false);
    }//GEN-LAST:event_StudentAttendanceFeatureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassFeature;
    private javax.swing.JPanel EmployeeAttendanceFeature;
    private javax.swing.JPanel EmployeeFeature;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JPanel StudentAttendanceFeature;
    private javax.swing.JPanel StudentDataFeature;
    private javax.swing.JLabel StudentFeature;
    private javax.swing.JPanel SubjectFeature;
    private javax.swing.JPanel SubjectScheduleFeature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
