package com.SchoolManagementSystem.Views;

import javax.swing.table.DefaultTableModel;

import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import com.SchoolManagementSystem.Views.DashboardView;

import com.SchoolManagementSystem.Dtos.EmployeeDto;
import com.SchoolManagementSystem.Helpers.CachingService;
import com.SchoolManagementSystem.Repositories.EmployeeRepositories;

public class EmployeeView extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    
    // Employee Repositories
    private final EmployeeRepositories employeeRepositories =
        new EmployeeRepositories();
    
    // Employee DTOs
    private EmployeeDto employeeDto = new EmployeeDto();
    
    private ArrayList<String> employeeIdLists = new ArrayList<>();
    
    public EmployeeView() {
        initComponents();
        this.setTitle("Data Guru dan Pegawai");
        TableHandler("default", null);
    }
    
    private void TableHandler(String mode, String search) {
        tableModel = new DefaultTableModel();
        EmployeeTable.setModel(tableModel);
        
        String[] columnNames = {
            "Nomor",
            "NIP",
            "Nama",
            "Tgl. Lahir",
            "Jenis Kelamin",
            "Jenis Perkerjaan",
            "No. HP",
            "Alamat"
        };
        
        tableModel.setColumnIdentifiers(columnNames);
        
        List<EmployeeDto> employeeDataList;
        if (mode.equals("searching")) {
            employeeDataList = employeeRepositories
                .searchEmployeesRepository(search);
        } else {
            employeeDataList = employeeRepositories
                .getEmployeesRepository();
        }
        
        int index = 1;
        employeeIdLists = new ArrayList<>();
        for (EmployeeDto employeeData : employeeDataList) {
            String employeeId      = employeeData.getEmployeeId();
            String employeeNip     = employeeData.getEmployeeNip();
            String employeeName    = employeeData.getEmployeeName();
            String employeeBirth   = employeeData.getEmployeeBirthDate();
            String employeeGender  = employeeData.getEmployeeGender();
            String employeeType    = employeeData.getEmployeeType();
            String employeePhone   = employeeData.getEmployeePhone();
            String employeeAddress = employeeData.getEmployeeAddress();
            
            tableModel.addRow(new Object[]{
                index, employeeNip, employeeName, employeeBirth,
                employeeGender, employeeType, employeePhone, employeeAddress
            });
            
            employeeIdLists.add(employeeId);
            index ++;
        }
    }
    
    private void postAction(boolean condition, String message) {
        employeeDto = new EmployeeDto();
        CachingService.clear();
        TableHandler("default", null);
        
        if (condition) {
            JOptionPane.showMessageDialog(
                this, 
                message,
                "Berhasil...",
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                this, 
                message,
                "Gagal...",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameRoomLabel = new javax.swing.JLabel();
        EmployeeNipTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        EmployeeNameTextField = new javax.swing.JTextField();
        NameRoomLabel2 = new javax.swing.JLabel();
        NameRoomLabel3 = new javax.swing.JLabel();
        EmployeeBirthTextField = new javax.swing.JTextField();
        NameRoomLabel6 = new javax.swing.JLabel();
        EmployeeTypeComboBox = new javax.swing.JComboBox<>();
        EmployeePhoneTextField = new javax.swing.JTextField();
        NameRoomLabel7 = new javax.swing.JLabel();
        EmployeeGenderComboBox = new javax.swing.JComboBox<>();
        NameRoomLabel4 = new javax.swing.JLabel();
        NameRoomLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeAddressTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        NameRoomLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel.setText("NIP");

        EmployeeNipTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeNipTextField.setForeground(new java.awt.Color(86, 85, 191));
        EmployeeNipTextField.setText("  Masukan NIP ...");
        EmployeeNipTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        EmployeeNipTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeNipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeNipTextFieldActionPerformed(evt);
            }
        });

        EmployeeTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "NIP", "Nama", "Tgl. Lahir", "Jenis Kelamin", "Jenis Perkerjaan", "No. HP", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(EmployeeTable);

        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(86, 85, 191));
        SearchTextField.setText("  Cari Guru dan Pegawai ...");
        SearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(86, 85, 191));
        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Cari");
        SearchButton.setBorder(null);
        SearchButton.setBorderPainted(false);
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(86, 85, 191));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Tambah");
        AddButton.setBorder(null);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(86, 85, 191));
        ResetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.setBorder(null);
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(86, 85, 191));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Hapus");
        DeleteButton.setBorder(null);
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(86, 85, 191));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setText("Edit");
        EditButton.setBorder(null);
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(86, 85, 191));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Guru dan Pegawai");

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("  Kembali  ");
        BackButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        EmployeeNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeNameTextField.setForeground(new java.awt.Color(86, 85, 191));
        EmployeeNameTextField.setText("  Masukan Nama ...");
        EmployeeNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        EmployeeNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeNameTextFieldActionPerformed(evt);
            }
        });

        NameRoomLabel2.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel2.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel2.setText("Nama Guru / Pegawai");

        NameRoomLabel3.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel3.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel3.setText("Perkerjaan");

        EmployeeBirthTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeBirthTextField.setForeground(new java.awt.Color(86, 85, 191));
        EmployeeBirthTextField.setText("  Masukan Tanggal Lahir ...");
        EmployeeBirthTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        EmployeeBirthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeBirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeBirthTextFieldActionPerformed(evt);
            }
        });

        NameRoomLabel6.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel6.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel6.setText("Tanggal Lahir (Th/Bb/Tgl)");

        EmployeeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guru", "Tata Usaha", "Admin", "Satpam", "Kebersihan" }));
        EmployeeTypeComboBox.setBorder(null);
        EmployeeTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeTypeComboBoxActionPerformed(evt);
            }
        });

        EmployeePhoneTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeePhoneTextField.setForeground(new java.awt.Color(86, 85, 191));
        EmployeePhoneTextField.setText("  Masukan No. handphone ...");
        EmployeePhoneTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        EmployeePhoneTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeePhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeePhoneTextFieldActionPerformed(evt);
            }
        });

        NameRoomLabel7.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel7.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel7.setText("No. Handphone");

        EmployeeGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        EmployeeGenderComboBox.setBorder(null);

        NameRoomLabel4.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel4.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel4.setText("Jenis Kelamin");

        NameRoomLabel5.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel5.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel5.setText("Alamat");

        EmployeeAddressTextArea.setColumns(20);
        EmployeeAddressTextArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeAddressTextArea.setForeground(new java.awt.Color(86, 85, 191));
        EmployeeAddressTextArea.setRows(5);
        EmployeeAddressTextArea.setText("  Masukan Alamat ...");
        EmployeeAddressTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        jScrollPane1.setViewportView(EmployeeAddressTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameRoomLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeNipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameRoomLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EmployeePhoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NameRoomLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameRoomLabel6))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(EmployeeBirthTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(35, 35, 35))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NameRoomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NameRoomLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmployeeNipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NameRoomLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmployeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(NameRoomLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeeBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeeGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(NameRoomLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeNipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeNipTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeNipTextFieldActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void EmployeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTableMouseClicked
        int selectedRow = EmployeeTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane
                .showMessageDialog(this, 
                "Pilih baris yang ingin diupdate.");
        }
        
        CachingService.put("employeeId", employeeIdLists.get(
                (int) tableModel.getValueAt(selectedRow, 0) - 1
            )
        );
        
        EmployeeNipTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 1));
        EmployeeNameTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 2));
        EmployeeBirthTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 3));
        EmployeeGenderComboBox.setSelectedItem(
            (Object) tableModel.getValueAt(selectedRow, 4));
        EmployeeTypeComboBox.setSelectedItem(
            (Object) tableModel.getValueAt(selectedRow, 5));
        EmployeePhoneTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 6));
        EmployeeAddressTextArea.setText(
            (String) tableModel.getValueAt(selectedRow, 7));
    }//GEN-LAST:event_EmployeeTableMouseClicked

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        employeeDto.setEmployeeNip(EmployeeNipTextField.getText());
        employeeDto.setEmployeeName(EmployeeNameTextField.getText());
        employeeDto.setEmployeeBirthDate(EmployeeBirthTextField.getText());
        employeeDto.setEmployeeGender(EmployeeGenderComboBox.getSelectedItem().toString());
        employeeDto.setEmployeeType(EmployeeTypeComboBox.getSelectedItem().toString());
        employeeDto.setEmployeePhone(EmployeePhoneTextField.getText());
        employeeDto.setEmployeeAddress(EmployeeAddressTextArea.getText());
        
        Map<String, Object> createEmployee = employeeRepositories
            .createEmployeeRepository(employeeDto);
        
        postAction(
            (boolean) createEmployee.get("result"),
            (String) createEmployee.get("message")
        );
    }//GEN-LAST:event_AddButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        EmployeeTypeComboBox.setSelectedItem((Object) "Guru");
        EmployeeNipTextField.setText("  Masukan NIP ...");
        EmployeeNameTextField.setText("  Masukan Nama ...");
        EmployeeBirthTextField.setText("  Masukan Tanggal Lahir ...");
        EmployeeGenderComboBox.setSelectedItem((Object) "Laki - Laki");
        EmployeePhoneTextField.setText("  Masukan No. handphone ...");
        EmployeeAddressTextArea.setText("  Masukan Alamat ...");
        SearchTextField.setText("  Cari Guru dan Pegawai ...");
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        boolean deleteEmployee = employeeRepositories
            .deleteEmployeeRepository((String) CachingService.get("employeeId"));
        
        postAction(
            deleteEmployee,
            "Data Berhasil Di Hapus !!!."
        );
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        employeeDto.setEmployeeId((String) CachingService.get("employeeId"));
        
        employeeDto.setEmployeeNip(EmployeeNipTextField.getText());
        employeeDto.setEmployeeName(EmployeeNameTextField.getText());
        employeeDto.setEmployeeBirthDate(EmployeeBirthTextField.getText());
        employeeDto.setEmployeeGender(EmployeeGenderComboBox.getSelectedItem().toString());
        employeeDto.setEmployeeType(EmployeeTypeComboBox.getSelectedItem().toString());
        employeeDto.setEmployeePhone(EmployeePhoneTextField.getText());
        employeeDto.setEmployeeAddress(EmployeeAddressTextArea.getText());
        
        Map<String, Object> updateEmployee = employeeRepositories
            .updateEmployeeRepository(employeeDto);
        
        postAction(
            (boolean) updateEmployee.get("result"),
            (String) updateEmployee.get("message")
        );
    }//GEN-LAST:event_EditButtonMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        TableHandler("searching", SearchTextField.getText());
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        DashboardView dashboardView = new DashboardView();
            
        dashboardView.setVisible(true);
        dashboardView.setResizable(false);
        dashboardView.pack();
        dashboardView.setLocationRelativeTo(null);
        dashboardView.setDefaultCloseOperation(dashboardView.EXIT_ON_CLOSE);

        this.setVisible(false);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void EmployeeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeNameTextFieldActionPerformed

    private void EmployeeBirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeBirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeBirthTextFieldActionPerformed

    private void EmployeePhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeePhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeePhoneTextFieldActionPerformed

    private void EmployeeTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeTypeComboBoxActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel BackButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextArea EmployeeAddressTextArea;
    private javax.swing.JTextField EmployeeBirthTextField;
    private javax.swing.JComboBox<String> EmployeeGenderComboBox;
    private javax.swing.JTextField EmployeeNameTextField;
    private javax.swing.JTextField EmployeeNipTextField;
    private javax.swing.JTextField EmployeePhoneTextField;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JComboBox<String> EmployeeTypeComboBox;
    private javax.swing.JLabel NameRoomLabel;
    private javax.swing.JLabel NameRoomLabel2;
    private javax.swing.JLabel NameRoomLabel3;
    private javax.swing.JLabel NameRoomLabel4;
    private javax.swing.JLabel NameRoomLabel5;
    private javax.swing.JLabel NameRoomLabel6;
    private javax.swing.JLabel NameRoomLabel7;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
