package com.SchoolManagementSystem.Views;

import javax.swing.table.DefaultTableModel;

import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import com.SchoolManagementSystem.Views.DashboardView;

import com.SchoolManagementSystem.Dtos.StudentDto;
import com.SchoolManagementSystem.Helpers.CachingService;
import com.SchoolManagementSystem.Repositories.StudentRepositories;

public class StudentView extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    
    // Classes Repositories
    private final StudentRepositories studentRepositories =
        new StudentRepositories();
    
    // Classes DTOs
    private StudentDto studentDto = new StudentDto();
    
    private ArrayList<String> studentIdLists = new ArrayList<>();
    private ArrayList<String> classNameLists = new ArrayList<>();
    
    public StudentView() {
        initComponents();
        this.setTitle("Data Siswa");
        TableHandler("default", null);
        ClassComboBoxHandler();
    }
    
    private void ClassComboBoxHandler() {           
        for (String className: classNameLists) {
            if (StudentClassComboBox.getItemCount() >= classNameLists.size()) {
                StudentClassComboBox.removeAllItems();
            }
                
            StudentClassComboBox.addItem(className);
        }
    }
    
    private void TableHandler(String mode, String search) {
        tableModel = new DefaultTableModel();
        StudentTable.setModel(tableModel);
        
        String[] columnNames = {
            "Nomor",
            "Kelas",
            "NISN",
            "Nama",
            "Tgl. Lahir",
            "Jenis Kelamin",
            "No. HP",
            "Alamat"
        };
        
        tableModel.setColumnIdentifiers(columnNames);
        
        List<StudentDto> studentDataList;
        if (mode.equals("searching")) {
            studentDataList = studentRepositories
                .searchStudentsRepository(search);
        } else {
            studentDataList = studentRepositories
            .getStudentsRepository();
        }
        
        int index = 1;
        studentIdLists = new ArrayList<>();
        for (StudentDto studentData : studentDataList) {
            String studentId      = studentData.getStudentId();
            String className      = studentData.getClassName();
            String studentNisn    = studentData.getStudentNisn();
            String studentName    = studentData.getStudentName();
            String studentBirth   = studentData.getStudentBirth();
            String studentGender  = studentData.getStudentGender();
            String studentPhone   = studentData.getStudentPhone();
            String studentAddress = studentData.getStudentAddress();
            
            tableModel.addRow(new Object[]{
                index, className, studentNisn, studentName,
                studentBirth, studentGender, studentPhone, studentAddress
            });
            
            studentIdLists.add(studentId);
            classNameLists.add(className);
            index ++;
        }
    }
    
    private void postAction(boolean condition, String message) {
        studentDto = new StudentDto();
        CachingService.clear();
        TableHandler("default", null);
        
        if (condition) {
            JOptionPane.showMessageDialog(
                this, 
                message,
                "Berhasil...",
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                this, 
                message,
                "Gagal...",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameRoomLabel = new javax.swing.JLabel();
        StudentNisnTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameRoomLabel1 = new javax.swing.JLabel();
        StudentNameTextField = new javax.swing.JTextField();
        NameRoomLabel2 = new javax.swing.JLabel();
        NameRoomLabel3 = new javax.swing.JLabel();
        StudentBirthTextField = new javax.swing.JTextField();
        NameRoomLabel6 = new javax.swing.JLabel();
        StudentClassComboBox = new javax.swing.JComboBox<>();
        StudentPhoneTextField = new javax.swing.JTextField();
        NameRoomLabel7 = new javax.swing.JLabel();
        StudentGenderComboBox = new javax.swing.JComboBox<>();
        NameRoomLabel4 = new javax.swing.JLabel();
        NameRoomLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentAddressTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        NameRoomLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel.setText("NISN");

        StudentNisnTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StudentNisnTextField.setForeground(new java.awt.Color(86, 85, 191));
        StudentNisnTextField.setText("  Masukan NISN Siswa ...");
        StudentNisnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        StudentNisnTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentNisnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNisnTextFieldActionPerformed(evt);
            }
        });

        StudentTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Kelas", "NISN", "Nama", "Tgl. Lahir", "Jenis kelamin", "No. HP", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(StudentTable);

        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchTextField.setForeground(new java.awt.Color(86, 85, 191));
        SearchTextField.setText("  Cari Siswa ...");
        SearchTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(86, 85, 191));
        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Cari");
        SearchButton.setBorder(null);
        SearchButton.setBorderPainted(false);
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(86, 85, 191));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Tambah");
        AddButton.setBorder(null);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        ResetButton.setBackground(new java.awt.Color(86, 85, 191));
        ResetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetButton.setText("Reset");
        ResetButton.setBorder(null);
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(86, 85, 191));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Hapus");
        DeleteButton.setBorder(null);
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(86, 85, 191));
        EditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setText("Edit");
        EditButton.setBorder(null);
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(86, 85, 191));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Siswa");

        NameRoomLabel1.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        NameRoomLabel1.setText("  Kembali  ");
        NameRoomLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        NameRoomLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NameRoomLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameRoomLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NameRoomLabel1)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameRoomLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        StudentNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StudentNameTextField.setForeground(new java.awt.Color(86, 85, 191));
        StudentNameTextField.setText("  Masukan Nama Siswa ...");
        StudentNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        StudentNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNameTextFieldActionPerformed(evt);
            }
        });

        NameRoomLabel2.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel2.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel2.setText("Nama Siswa");

        NameRoomLabel3.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel3.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel3.setText("Kelas Siswa");

        StudentBirthTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StudentBirthTextField.setForeground(new java.awt.Color(86, 85, 191));
        StudentBirthTextField.setText("  Masukan Tanggal Lahir ...");
        StudentBirthTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        StudentBirthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentBirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentBirthTextFieldActionPerformed(evt);
            }
        });

        NameRoomLabel6.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel6.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel6.setText("Tanggal Lahir (Th/Bb/Tgl)");

        StudentClassComboBox.setBorder(null);

        StudentPhoneTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StudentPhoneTextField.setForeground(new java.awt.Color(86, 85, 191));
        StudentPhoneTextField.setText("  Masukan No. handphone ...");
        StudentPhoneTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        StudentPhoneTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentPhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPhoneTextFieldActionPerformed(evt);
            }
        });

        NameRoomLabel7.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel7.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel7.setText("No. Handphone");

        StudentGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        StudentGenderComboBox.setBorder(null);

        NameRoomLabel4.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel4.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel4.setText("Jenis Kelamin");

        NameRoomLabel5.setBackground(new java.awt.Color(255, 255, 255));
        NameRoomLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameRoomLabel5.setForeground(new java.awt.Color(86, 85, 191));
        NameRoomLabel5.setText("Alamat");

        StudentAddressTextArea.setColumns(20);
        StudentAddressTextArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StudentAddressTextArea.setForeground(new java.awt.Color(86, 85, 191));
        StudentAddressTextArea.setRows(5);
        StudentAddressTextArea.setText("  Masukan Alamat ...");
        StudentAddressTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 85, 191), 2, true));
        jScrollPane1.setViewportView(StudentAddressTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameRoomLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentNisnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameRoomLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentPhoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StudentNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NameRoomLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameRoomLabel6))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(StudentBirthTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(35, 35, 35))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NameRoomLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NameRoomLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StudentNisnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NameRoomLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StudentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(NameRoomLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameRoomLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(NameRoomLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentNisnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNisnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNisnTextFieldActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        int selectedRow = StudentTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane
                .showMessageDialog(this, 
                "Pilih baris yang ingin diupdate.");
        }
        
        CachingService.put("studentId", studentIdLists.get(
                (int) tableModel.getValueAt(selectedRow, 0) - 1
            )
        );

        StudentClassComboBox.setSelectedItem(
            (Object) tableModel.getValueAt(selectedRow, 1));
        StudentNisnTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 2));
        StudentNameTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 3));
        StudentBirthTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 4));
        StudentGenderComboBox.setSelectedItem(
            (Object) tableModel.getValueAt(selectedRow, 5));
        StudentPhoneTextField.setText(
            (String) tableModel.getValueAt(selectedRow, 6));
        StudentAddressTextArea.setText(
            (String) tableModel.getValueAt(selectedRow, 7));
    }//GEN-LAST:event_StudentTableMouseClicked

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        studentDto.setClassName(StudentClassComboBox.getSelectedItem().toString());
        studentDto.setStudentNisn(StudentNisnTextField.getText());
        studentDto.setStudentName(StudentNameTextField.getText());
        studentDto.setStudentBirth(StudentBirthTextField.getText());
        studentDto.setStudentGender(StudentGenderComboBox.getSelectedItem().toString());
        studentDto.setStudentPhone(StudentPhoneTextField.getText());
        studentDto.setStudentAddress(StudentAddressTextArea.getText());
        
        Map<String, Object> createStudent = studentRepositories
            .createStudentRepository(studentDto);
        
        postAction(
            (boolean) createStudent.get("result"),
            (String) createStudent.get("message")
        );
    }//GEN-LAST:event_AddButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        StudentClassComboBox.setSelectedItem((Object) classNameLists.get(0));
        StudentNisnTextField.setText("  Masukan NISN Siswa ...");
        StudentNameTextField.setText("  Masukan Nama Siswa ...");
        StudentBirthTextField.setText("  Masukan Tanggal Lahir ...");
        StudentGenderComboBox.setSelectedItem((Object) "Laki - Laki");
        StudentPhoneTextField.setText("  Masukan No. handphone ...");
        StudentAddressTextArea.setText("  Masukan Alamat ...");
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        boolean deleteStudent = studentRepositories
            .deleteStudentRepository((String) CachingService.get("studentId"));
        
        postAction(
            deleteStudent,
            "Data Berhasil Di Hapus !!!."
        );
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        studentDto.setStudentId((String) CachingService.get("studentId"));
        
        studentDto.setClassName(StudentClassComboBox.getSelectedItem().toString());
        studentDto.setStudentNisn(StudentNisnTextField.getText());
        studentDto.setStudentName(StudentNameTextField.getText());
        studentDto.setStudentBirth(StudentBirthTextField.getText());
        studentDto.setStudentGender(StudentGenderComboBox.getSelectedItem().toString());
        studentDto.setStudentPhone(StudentPhoneTextField.getText());
        studentDto.setStudentAddress(StudentAddressTextArea.getText());
        
        Map<String, Object> updateStudent = studentRepositories
            .updateStudentRepository(studentDto);
        
        postAction(
            (boolean) updateStudent.get("result"),
            (String) updateStudent.get("message")
        );
    }//GEN-LAST:event_EditButtonMouseClicked

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        TableHandler("searching", SearchTextField.getText());
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void NameRoomLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameRoomLabel1MouseClicked
        DashboardView dashboardView = new DashboardView();
            
        dashboardView.setVisible(true);
        dashboardView.setResizable(false);
        dashboardView.pack();
        dashboardView.setLocationRelativeTo(null);
        dashboardView.setDefaultCloseOperation(dashboardView.EXIT_ON_CLOSE);

        this.setVisible(false);
    }//GEN-LAST:event_NameRoomLabel1MouseClicked

    private void StudentNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNameTextFieldActionPerformed

    private void StudentBirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentBirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentBirthTextFieldActionPerformed

    private void StudentPhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentPhoneTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel NameRoomLabel;
    private javax.swing.JLabel NameRoomLabel1;
    private javax.swing.JLabel NameRoomLabel2;
    private javax.swing.JLabel NameRoomLabel3;
    private javax.swing.JLabel NameRoomLabel4;
    private javax.swing.JLabel NameRoomLabel5;
    private javax.swing.JLabel NameRoomLabel6;
    private javax.swing.JLabel NameRoomLabel7;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JTextArea StudentAddressTextArea;
    private javax.swing.JTextField StudentBirthTextField;
    private javax.swing.JComboBox<String> StudentClassComboBox;
    private javax.swing.JComboBox<String> StudentGenderComboBox;
    private javax.swing.JTextField StudentNameTextField;
    private javax.swing.JTextField StudentNisnTextField;
    private javax.swing.JTextField StudentPhoneTextField;
    private javax.swing.JTable StudentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
